# Generated by Django 3.0.5 on 2020-04-18 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_user_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_category',
        ),
    ]
