# Generated by Django 3.0.5 on 2020-04-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_user_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_categpry',
            field=models.CharField(default='customer', max_length=100),
        ),
    ]
