# Generated by Django 3.0.5 on 2020-04-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200418_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_category',
            field=models.CharField(default='Customer', max_length=100),
        ),
    ]
