# Generated by Django 3.0.5 on 2020-04-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupan', '0002_auto_20200416_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='profile@example.com', max_length=254, unique=True, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
