# Generated by Django 3.0.5 on 2020-04-17 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupan', '0003_profile_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
