# Generated by Django 3.0.5 on 2020-04-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupan', '0005_auto_20200418_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupan',
            name='description',
            field=models.TextField(default='Description'),
            preserve_default=False,
        ),
    ]
