# Generated by Django 3.0.5 on 2020-04-20 10:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coupan', '0022_auto_20200418_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupan',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 21, 10, 32, 33, 341818, tzinfo=utc)),
        ),
    ]
